# Dependencies
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true
plugins:          [jekyll-paginate, pygments.rb]

# Setup
title:            Zeměkvět
tagline:          ''
description:      ''
url:              http://www.zemekvet.cz
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

safe:             true
paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

support_url:
  url:            /podpora

documents_url:
  url:            /dokumenty

contributions_url:
  url:            /prispevky

projects_url:
  url:            /projekty

contact_url:
  url:            /kontakt

logotypes_url:
  url:            /logotypy
