# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true
plugins:          [jekyll-paginate, redcarpet, pygments.rb]

# Setup
title:            Zeměkvět
tagline:          ''
description:      ''
url:              http://www.zemekvet.cz
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

support:
  url:            /podpora

docs:
  url:            /dokumenty

projects:
  url:            /projekty

contact:
  url:            /kontakt

logotypes:
  url:            /logotypy

akce:
  url:            /
